import "./globals.css";
import { Inter } from "next/font/google";
import Banner from "./components/Banner";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import { defaultCollections } from "@next-auth/mongodb-adapter";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "타입앱",
  description: "Generated by create next app",
};

export default RootLayout;

async function RootLayout({ children }: { children: React.ReactNode }) {
  let session = await getServerSession(authOptions);

  return (
    <html>
      <body className={inter.className}>
        <Banner session={session} />

        <div id="modal-root" />
        {children}
      </body>
    </html>
  );
}
